
version: "3.3"

networks:
  network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/wordpress
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/adminer
      o: bind

services:
  nginx:
    container_name: nginx
    restart: always
    build: ./requirements/nginx/
    networks:
      - network
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - adminer:/var/www/adminer

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

# Bonus
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - mariadb
    networks:
      - network
    volumes:
      - adminer:/var/www/adminer
    restart: always
