
version: "3.3"

networks:
  network:
    driver: bridge

# volumes:
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/yrabby/data/mysql
#       o: bind
#   wordpress_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/yrabby/data/wordpress
#       o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    networks:
      - network
    ports:
      - 443:443
    env_file:
      - .env

  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   networks:
  #     - network
  #   restart: always
  #   env_file:
  #     - .env

  # wordpress:
  #   container_name: wordpress
  #   depends_on:
  #     - mariadb
  #   build: ./requirements/wordpress/
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - network
