
version: "3.3"

networks:
  network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/wordpress
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/yrabby/data/adminer
      o: bind

services:
  nginx:
    container_name: nginx
    restart: always
    build: ./requirements/nginx/
    networks:
      - network
    ports:
      - 3001:3001
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - adminer:/var/www/adminer

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

# Bonus
  adminer:
    container_name: adminer
    restart: always
    build: ./requirements/bonus/adminer/
    depends_on:
      - mariadb
    networks:
      - network
    volumes:
      - adminer:/var/www/adminer
  
  ftp:
    container_name: ftp
    restart: always
    build: ./requirements/bonus/ftp/
    depends_on:
      - wordpress
    networks:
      - network
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env

  redis:
    container_name: redis
    restart: always
    build: ./requirements/bonus/redis/
    depends_on:
      - wordpress
    networks:
      - network

  site:
    container_name: site
    restart: always
    build: ./requirements/bonus/site/
    ports:
      - 8081:80
    networks:
      - network

  uptime-kuma:
    container_name: uptime-kuma
    restart: always
    build: ./requirements/bonus/uptime-kuma/
    networks:
      - network
